# Generated by Django 5.2.6 on 2025-09-27 15:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0032_remove_academicyear_settings_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المادة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='الشخص المسؤول')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='المؤلف')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='الناشر')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='الرقم الدولي')),
                ('book_type', models.CharField(choices=[('TEXTBOOK', 'كتاب مدرسي'), ('WORKBOOK', 'كتاب تمارين'), ('REFERENCE', 'كتاب مرجعي'), ('DICTIONARY', 'قاموس'), ('ATLAS', 'أطلس'), ('OTHER', 'أخرى')], default='TEXTBOOK', max_length=15, verbose_name='نوع الكتاب')),
                ('total_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي المخزون')),
                ('available_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المتاح للتوزيع')),
                ('distributed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الموزع')),
                ('damaged_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التالف')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سعر التكلفة')),
                ('minimum_stock_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('grade_levels', models.ManyToManyField(blank=True, to='school_settings.gradelevel', verbose_name='الصفوف الدراسية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.subject', verbose_name='المادة الدراسية')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الكراسة')),
                ('notebook_type', models.CharField(choices=[('LINED', 'مسطر'), ('SQUARED', 'مربعات'), ('BLANK', 'أبيض'), ('DRAWING', 'رسم'), ('MUSIC', 'موسيقى'), ('OTHER', 'أخرى')], max_length=10, verbose_name='نوع الكراسة')),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('B5', 'B5'), ('SMALL', 'صغير'), ('MEDIUM', 'متوسط'), ('LARGE', 'كبير')], default='A4', max_length=10, verbose_name='الحجم')),
                ('pages_count', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الصفحات')),
                ('total_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي المخزون')),
                ('available_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المتاح للتوزيع')),
                ('distributed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الموزع')),
                ('damaged_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التالف')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر التكلفة')),
                ('minimum_stock_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('grade_levels', models.ManyToManyField(blank=True, to='school_settings.gradelevel', verbose_name='الصفوف الدراسية')),
            ],
            options={
                'verbose_name': 'كراسة',
                'verbose_name_plural': 'الكراسات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الأداة')),
                ('category', models.CharField(choices=[('STATIONERY', 'أدوات مكتبية'), ('ART', 'أدوات فنية'), ('SCIENCE', 'أدوات علمية'), ('SPORTS', 'أدوات رياضية'), ('ELECTRONICS', 'إلكترونيات'), ('CLEANING', 'أدوات تنظيف'), ('OTHER', 'أخرى')], max_length=15, verbose_name='الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('unit', models.CharField(default='قطعة', max_length=20, verbose_name='الوحدة')),
                ('total_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي المخزون')),
                ('available_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المتاح للتوزيع')),
                ('distributed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الموزع')),
                ('damaged_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التالف')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سعر التكلفة')),
                ('minimum_stock_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('grade_levels', models.ManyToManyField(blank=True, to='school_settings.gradelevel', verbose_name='الصفوف الدراسية')),
            ],
            options={
                'verbose_name': 'أداة مدرسية',
                'verbose_name_plural': 'الأدوات المدرسية',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الإيصال')),
                ('receipt_type', models.CharField(choices=[('BOOKS', 'كتب'), ('NOTEBOOKS', 'كراسات'), ('SUPPLIES', 'أدوات مدرسية')], max_length=15, verbose_name='نوع البضاعة')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي الكمية')),
                ('damaged_items', models.IntegerField(default=0, verbose_name='الكمية التالفة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مستلم بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'إيصال استلام',
                'verbose_name_plural': 'إيصالات الاستلام',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستلمة')),
                ('quantity_damaged', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية التالفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='إجمالي التكلفة')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.notebook', verbose_name='الكراسة')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_items', to='books_inventory.stockreceipt', verbose_name='الإيصال')),
            ],
            options={
                'verbose_name': 'عنصر استلام كراسة',
                'verbose_name_plural': 'عناصر استلام الكراسات',
            },
        ),
        migrations.CreateModel(
            name='BookReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستلمة')),
                ('quantity_damaged', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية التالفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.book', verbose_name='الكتاب')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='books_inventory.stockreceipt', verbose_name='الإيصال')),
            ],
            options={
                'verbose_name': 'عنصر استلام كتاب',
                'verbose_name_plural': 'عناصر استلام الكتب',
            },
        ),
        migrations.CreateModel(
            name='StockShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('BOOK', 'كتاب'), ('NOTEBOOK', 'كراسة'), ('SUPPLY', 'أداة مدرسية')], max_length=10, verbose_name='نوع العنصر')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم العنصر')),
                ('current_stock', models.IntegerField(verbose_name='المخزون الحالي')),
                ('required_quantity', models.IntegerField(verbose_name='الكمية المطلوبة')),
                ('shortage_quantity', models.IntegerField(verbose_name='كمية النقص')),
                ('status', models.CharField(choices=[('REPORTED', 'مُبلغ عنه'), ('ACKNOWLEDGED', 'معترف به'), ('ORDERED', 'تم الطلب'), ('RESOLVED', 'تم الحل')], default='REPORTED', max_length=15, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('HIGH', 'عالي'), ('MEDIUM', 'متوسط'), ('LOW', 'منخفض')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_inventory.book', verbose_name='الكتاب')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_inventory.notebook', verbose_name='الكراسة')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مُبلغ بواسطة')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_inventory.schoolsupply', verbose_name='الأداة المدرسية')),
            ],
            options={
                'verbose_name': 'نقص في المخزون',
                'verbose_name_plural': 'النواقص في المخزون',
                'ordering': ['-reported_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='StudentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التوزيع')),
                ('first_installment_verified', models.BooleanField(default=False, verbose_name='تم التحقق من دفع القسط الأول')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('verification_notes', models.TextField(blank=True, verbose_name='ملاحظات التحقق')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('PARTIAL', 'موزع جزئياً'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=25, verbose_name='الحالة')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي العناصر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='موزع بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'توزيع الطالب',
                'verbose_name_plural': 'توزيعات الطلاب',
                'ordering': ['-distribution_date', '-created_at'],
                'unique_together': {('student', 'distribution_date')},
            },
        ),
        migrations.CreateModel(
            name='NotebookDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المطلوبة')),
                ('quantity_distributed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الموزعة')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='تم التوزيع')),
                ('distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوزيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.notebook', verbose_name='الكراسة')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_items', to='books_inventory.studentdistribution', verbose_name='التوزيع')),
            ],
            options={
                'verbose_name': 'توزيع كراسة',
                'verbose_name_plural': 'توزيعات الكراسات',
            },
        ),
        migrations.CreateModel(
            name='BookDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المطلوبة')),
                ('quantity_distributed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الموزعة')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='تم التوزيع')),
                ('distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوزيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.book', verbose_name='الكتاب')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='books_inventory.studentdistribution', verbose_name='التوزيع')),
            ],
            options={
                'verbose_name': 'توزيع كتاب',
                'verbose_name_plural': 'توزيعات الكتب',
            },
        ),
        migrations.CreateModel(
            name='SupplyDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المطلوبة')),
                ('quantity_distributed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الموزعة')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='تم التوزيع')),
                ('distribution_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوزيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='books_inventory.studentdistribution', verbose_name='التوزيع')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.schoolsupply', verbose_name='الأداة المدرسية')),
            ],
            options={
                'verbose_name': 'توزيع أداة مدرسية',
                'verbose_name_plural': 'توزيعات الأدوات المدرسية',
            },
        ),
        migrations.CreateModel(
            name='SupplyReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستلمة')),
                ('quantity_damaged', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية التالفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='books_inventory.stockreceipt', verbose_name='الإيصال')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.schoolsupply', verbose_name='الأداة المدرسية')),
            ],
            options={
                'verbose_name': 'عنصر استلام أداة مدرسية',
                'verbose_name_plural': 'عناصر استلام الأدوات المدرسية',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['subject', 'book_type'], name='books_inven_subject_1a9d51_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['available_stock'], name='books_inven_availab_c03dc4_idx'),
        ),
    ]
