# Generated by Django 5.2.6 on 2025-09-27 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='سنة الطبعة'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الصفحات'),
        ),
        migrations.AddField(
            model_name='book',
            name='term',
            field=models.CharField(choices=[('FIRST', 'الترم الأول'), ('SECOND', 'الترم الثاني'), ('FULL_YEAR', 'السنة كاملة')], default='FULL_YEAR', max_length=20, verbose_name='الفترة الدراسية'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('MINISTRY', 'كتاب وزاري'), ('WORKBOOK', 'كتاب تمارين وزاري'), ('MANAR_BOOK', 'كتاب المنار'), ('MANAR_SUMMARY', 'ملخص المنار'), ('MANAR_EXERCISES', 'تمارين المنار'), ('REFERENCE', 'كتاب مرجعي'), ('DICTIONARY', 'قاموس'), ('ATLAS', 'أطلس'), ('OTHER', 'أخرى')], default='MINISTRY', max_length=20, verbose_name='نوع الكتاب'),
        ),
    ]
