# Generated by Django 5.2.6 on 2025-09-27 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_inventory', '0003_subject_color_subject_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('BOOK', 'كتاب'), ('NOTEBOOK', 'كراسة'), ('SUPPLY', 'أداة مدرسية')], max_length=20, verbose_name='نوع العنصر')),
                ('item_id', models.PositiveIntegerField(verbose_name='معرف العنصر')),
                ('item_name', models.CharField(max_length=255, verbose_name='اسم العنصر')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='المخزون الحالي')),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('priority', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('URGENT', 'عاجل')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('IN_PROGRESS', 'قيد المعالجة'), ('RESOLVED', 'تم الحل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مُبلغ بواسطة')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_shortages', to=settings.AUTH_USER_MODEL, verbose_name='حُل بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير نقص',
                'verbose_name_plural': 'تقارير النقص',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['status', 'item_type'], name='books_inven_status_f701e9_idx'), models.Index(fields=['priority', 'report_date'], name='books_inven_priorit_33bb05_idx')],
            },
        ),
    ]
