# Generated by Django 5.2.6 on 2025-09-27 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_inventory', '0004_shortagereport'),
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='education_levels',
            field=models.ManyToManyField(blank=True, help_text='المراحل التعليمية التي تتضمن هذه المادة', to='school_settings.educationlevel', verbose_name='المراحل التعليمية'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, help_text='الصفوف التي تُدرّس فيها هذه المادة', to='school_settings.gradelevel', verbose_name='الصفوف الدراسية'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core_subject',
            field=models.BooleanField(default=True, help_text='هل هذه مادة أساسية أم اختيارية', verbose_name='مادة أساسية'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='عدد الحصص الأسبوعية'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#007bff', help_text='لون المادة في الواجهة', max_length=7, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_core_subject'], name='books_inven_is_core_54c59d_idx'),
        ),
    ]
