# Generated by Django 4.1.3 on 2025-09-24 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_notification_days', models.IntegerField(default=7, verbose_name='تنبيه قبل موعد الاستحقاق (أيام)')),
                ('overdue_payment_notification', models.BooleanField(default=True, verbose_name='تنبيه المتأخرات')),
                ('low_balance_notification', models.BooleanField(default=True, verbose_name='تنبيه الرصيد المنخفض')),
                ('new_student_registration_notification', models.BooleanField(default=True, verbose_name='تنبيه تسجيل طالب جديد')),
                ('notification_method', models.CharField(choices=[('EMAIL', 'بريد إلكتروني'), ('SMS', 'رسائل نصية'), ('SYSTEM', 'إشعارات النظام')], default='SYSTEM', max_length=10, verbose_name='وسيلة التنبيه')),
                ('email_host', models.CharField(blank=True, max_length=100, verbose_name='خادم البريد')),
                ('email_port', models.IntegerField(default=587, verbose_name='منفذ البريد')),
                ('email_username', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('email_password', models.CharField(blank=True, max_length=100, verbose_name='كلمة المرور')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='استخدام TLS')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات التنبيهات',
                'verbose_name_plural': 'إعدادات التنبيهات',
            },
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='تنسيق التصدير الافتراضي')),
                ('reports_per_page', models.IntegerField(default=50, verbose_name='عدد السجلات لكل صفحة')),
                ('include_school_logo_in_reports', models.BooleanField(default=True, verbose_name='تضمين شعار المدرسة في التقارير')),
                ('financial_reports_show_details', models.BooleanField(default=True, verbose_name='إظهار التفاصيل في التقارير المالية')),
                ('group_payments_by_month', models.BooleanField(default=True, verbose_name='تجميع المدفوعات حسب الشهر')),
                ('student_reports_include_photo', models.BooleanField(default=False, verbose_name='تضمين صور الطلاب')),
                ('show_parent_contact_info', models.BooleanField(default=True, verbose_name='إظهار معلومات اتصال ولي الأمر')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات التقارير',
                'verbose_name_plural': 'إعدادات التقارير',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8, verbose_name='الحد الأدنى لطول كلمة المرور')),
                ('require_special_characters', models.BooleanField(default=True, verbose_name='تطلب رموز خاصة')),
                ('require_numbers', models.BooleanField(default=True, verbose_name='تطلب أرقام')),
                ('password_expiry_days', models.IntegerField(default=90, verbose_name='انتهاء صلاحية كلمة المرور (أيام)')),
                ('session_timeout_minutes', models.IntegerField(default=30, verbose_name='انتهاء الجلسة (دقائق)')),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='الحد الأقصى لمحاولات تسجيل الدخول')),
                ('account_lockout_duration', models.IntegerField(default=30, verbose_name='مدة قفل الحساب (دقائق)')),
                ('log_user_actions', models.BooleanField(default=True, verbose_name='تسجيل أنشطة المستخدمين')),
                ('log_financial_transactions', models.BooleanField(default=True, verbose_name='تسجيل العمليات المالية')),
                ('backup_frequency_days', models.IntegerField(default=7, verbose_name='تكرار النسخ الاحتياطي (أيام)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الأمان',
                'verbose_name_plural': 'إعدادات الأمان',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='مدرسة المنار', max_length=200, verbose_name='اسم المدرسة')),
                ('school_name_en', models.CharField(default='Al-Manar School', max_length=200, verbose_name='اسم المدرسة بالإنجليزية')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_settings/', verbose_name='شعار المدرسة')),
                ('school_address', models.TextField(verbose_name='عنوان المدرسة')),
                ('school_phone', models.CharField(max_length=20, verbose_name='هاتف المدرسة')),
                ('school_email', models.EmailField(max_length=254, verbose_name='بريد إلكتروني')),
                ('school_website', models.URLField(blank=True, verbose_name='موقع المدرسة')),
                ('currency_symbol', models.CharField(default='ج.م', max_length=10, verbose_name='رمز العملة')),
                ('currency_name', models.CharField(default='جنيه مصري', max_length=50, verbose_name='اسم العملة')),
                ('default_installments_count', models.IntegerField(default=4, verbose_name='عدد الأقساط الافتراضي')),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة غرامة التأخير %')),
                ('grace_period_days', models.IntegerField(default=7, verbose_name='فترة السماح (أيام)')),
                ('academic_year_start_month', models.IntegerField(default=9, verbose_name='شهر بداية العام الدراسي')),
                ('academic_year_end_month', models.IntegerField(default=6, verbose_name='شهر نهاية العام الدراسي')),
                ('system_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='لغة النظام')),
                ('max_students_per_classroom', models.IntegerField(default=30, verbose_name='الحد الأقصى للطلاب بالفصل')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='محدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='SettingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تحديث'), ('DELETE', 'حذف')], max_length=10, verbose_name='نوع العملية')),
                ('setting_type', models.CharField(max_length=100, verbose_name='نوع الإعداد')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة السابقة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تغييرات الإعدادات',
                'verbose_name_plural': 'سجل تغييرات الإعدادات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
