# Generated by Django 4.1.3 on 2025-09-24 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'مدير النظام'), ('SCHOOL_MANAGER', 'مدير المدرسة'), ('ACCOUNTANT', 'موظف الحسابات'), ('STUDENT_AFFAIRS', 'موظف شؤون الطلاب'), ('BOOKS_INVENTORY', 'موظف مخزن الكتب'), ('UNIFORMS_INVENTORY', 'موظف مخزن الملابس')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دور المستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
            },
        ),
    ]
