# Generated by Django 5.2.6 on 2025-09-27 00:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_systemrole'),
        ('students', '0029_delete_tuition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: 2024-2025', max_length=20, verbose_name='العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('first_term_start', models.DateField(verbose_name='بداية الفصل الأول')),
                ('first_term_end', models.DateField(verbose_name='نهاية الفصل الأول')),
                ('second_term_start', models.DateField(verbose_name='بداية الفصل الثاني')),
                ('second_term_end', models.DateField(verbose_name='نهاية الفصل الثاني')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'العام الدراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المرحلة التعليمية')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='المرحلة بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='وصف المرحلة')),
                ('min_age', models.IntegerField(verbose_name='العمر الأدنى')),
                ('max_age', models.IntegerField(verbose_name='العمر الأقصى')),
                ('order', models.PositiveIntegerField(help_text='لترتيب المراحل في القوائم', verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'المرحلة التعليمية',
                'verbose_name_plural': 'المراحل التعليمية',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='academic_year_end_month',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='academic_year_start_month',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_footer_text',
            field=models.TextField(default='شكراً لكم على ثقتكم بنا', verbose_name='نص تذييل الإيصالات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_terms',
            field=models.TextField(blank=True, verbose_name='شروط وأحكام الإيصالات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='school_fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='فاكس المدرسة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='school_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school_settings/stamps/', verbose_name='ختم المدرسة'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_settings/logos/', verbose_name='شعار المدرسة'),
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصف')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='اسم الصف بالإنجليزية')),
                ('grade_number', models.IntegerField(help_text='مثال: 1 للصف الأول', verbose_name='رقم الصف')),
                ('typical_age', models.IntegerField(verbose_name='العمر المعتاد')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.educationlevel', verbose_name='المرحلة التعليمية')),
            ],
            options={
                'verbose_name': 'الصف الدراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['education_level__order', 'order'],
                'unique_together': {('education_level', 'grade_number')},
            },
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخصم')),
                ('category', models.CharField(choices=[('SIBLING', 'خصم الأشقاء'), ('FINANCIAL_HARDSHIP', 'خصم الحالة المالية'), ('ACADEMIC_EXCELLENCE', 'خصم التفوق الأكاديمي'), ('STAFF_CHILDREN', 'خصم أبناء الموظفين'), ('EARLY_PAYMENT', 'خصم الدفع المبكر'), ('LOYALTY', 'خصم الولاء'), ('OTHER', 'خصومات أخرى')], max_length=20, verbose_name='فئة الخصم')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED_AMOUNT', 'مبلغ ثابت')], max_length=15, verbose_name='نوع الخصم')),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='النسبة المئوية')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ الثابت')),
                ('applicable_to_fee_types', models.CharField(blank=True, help_text='فاصل بينها بفواصل', max_length=200, verbose_name='أنواع المصروفات المطبق عليها')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى لمبلغ الخصم')),
                ('min_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للمبلغ لتطبيق الخصم')),
                ('valid_from_date', models.DateField(verbose_name='صالح من تاريخ')),
                ('valid_to_date', models.DateField(verbose_name='صالح حتى تاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخصم')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('applicable_to_grades', models.ManyToManyField(blank=True, to='school_settings.gradelevel', verbose_name='الصفوف المطبق عليها')),
            ],
            options={
                'verbose_name': 'إعدادات الخصم',
                'verbose_name_plural': 'إعدادات الخصومات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFeesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('TUITION', 'مصروفات دراسية'), ('BOOKS', 'مصروفات كتب'), ('UNIFORMS', 'مصروفات ملابس'), ('TRANSPORT', 'مصروفات نقل'), ('MEALS', 'مصروفات وجبات'), ('ACTIVITIES', 'مصروفات أنشطة'), ('REGISTRATION', 'رسوم تسجيل'), ('OTHER', 'مصروفات أخرى')], max_length=20, verbose_name='نوع المصروفات')),
                ('fee_name', models.CharField(max_length=100, verbose_name='اسم المصروفات')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('installments_count', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط')),
                ('first_installment_due_date', models.DateField(verbose_name='تاريخ استحقاق القسط الأول')),
                ('installment_interval_days', models.IntegerField(default=30, verbose_name='فترة بين الأقساط (أيام)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إجباري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.gradelevel', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'إعدادات المصروفات',
                'verbose_name_plural': 'إعدادات المصروفات',
                'unique_together': {('academic_year', 'grade_level', 'fee_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الخصم المطبق')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الأصلي')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ النهائي')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('APPROVED', 'موافق عليه'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('application_reason', models.TextField(verbose_name='سبب التقدم للخصم')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL, verbose_name='موافق عليه بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discounts', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('discount_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.discountsettings', verbose_name='إعدادات الخصم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'خصم الطالب',
                'verbose_name_plural': 'خصومات الطلاب',
                'unique_together': {('student', 'discount_setting', 'academic_year')},
            },
        ),
    ]
