# Generated by Django 5.2.6 on 2025-09-27 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0003_academicyear_educationlevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrole',
            name='permissions',
            field=models.TextField(blank=True, help_text='JSON format للصلاحيات الخاصة', verbose_name='صلاحيات إضافية'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'مدير النظام'), ('SCHOOL_MANAGER', 'مدير المدرسة'), ('ACCOUNTANT', 'موظف الحسابات'), ('STUDENT_AFFAIRS', 'موظف شؤون الطلاب'), ('BOOKS_INVENTORY', 'موظف مخزن الكتب'), ('UNIFORMS_INVENTORY', 'موظف مخزن الملابس'), ('TEACHER', 'مدرس')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_address',
            field=models.TextField(blank=True, default='', verbose_name='عنوان المدرسة'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='بريد إلكتروني'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='هاتف المدرسة'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='محدث بواسطة'),
        ),
    ]
