# Generated by Django 5.2.6 on 2025-10-01 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل إعدادات', 'verbose_name_plural': 'سجلات الإعدادات'},
        ),
        migrations.AddField(
            model_name='settingslog',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف العملية'),
        ),
        migrations.AddField(
            model_name='settingslog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن'),
        ),
        migrations.AddField(
            model_name='settingslog',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الكائن'),
        ),
        migrations.AddField(
            model_name='settingslog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='معلومات المتصفح'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تحديث'), ('DELETE', 'حذف'), ('VIEW', 'عرض'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='setting_type',
            field=models.CharField(choices=[('ACADEMIC_YEAR', 'عام دراسي'), ('EDUCATION_LEVEL', 'مرحلة تعليمية'), ('GRADE_LEVEL', 'صف دراسي'), ('SCHOOL_FEE', 'مصروفات مدرسية'), ('DISCOUNT', 'خصم'), ('SYSTEM_SETTING', 'إعداد نظام'), ('USER_ROLE', 'دور مستخدم'), ('SCHOOL_INFO', 'معلومات المدرسة'), ('OTHER', 'أخرى')], default='OTHER', max_length=50, verbose_name='نوع الإعداد'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية'),
        ),
        migrations.AddIndex(
            model_name='settingslog',
            index=models.Index(fields=['user', 'timestamp'], name='school_sett_user_id_4de00d_idx'),
        ),
        migrations.AddIndex(
            model_name='settingslog',
            index=models.Index(fields=['action', 'timestamp'], name='school_sett_action_aaf4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='settingslog',
            index=models.Index(fields=['setting_type', 'timestamp'], name='school_sett_setting_512c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='settingslog',
            index=models.Index(fields=['-timestamp'], name='school_sett_timesta_7e40b0_idx'),
        ),
    ]
