# Generated by Django 5.2.6 on 2025-10-05 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0005_alter_settingslog_options_settingslog_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingslog',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='وصف العملية'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='new_value',
            field=models.TextField(blank=True, default='', verbose_name='القيمة الجديدة'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='اسم الكائن'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='old_value',
            field=models.TextField(blank=True, default='', verbose_name='القيمة السابقة'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='settingslog',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='معلومات المتصفح'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'مدير النظام'), ('SCHOOL_MANAGER', 'مدير المدرسة'), ('ACCOUNTANT', 'موظف الحسابات'), ('STUDENT_AFFAIRS', 'موظف شؤون الطلاب'), ('TREASURY_ADMIN', 'مدير الخزينة العام'), ('TREASURY_MANAGER', 'مدير الخزينة'), ('TREASURY_ACCOUNTANT', 'محاسب الخزينة'), ('TREASURY_CASHIER', 'أمين الخزينة'), ('TREASURY_VIEWER', 'مراجع الخزينة'), ('BOOKS_INVENTORY', 'موظف مخزن الكتب'), ('UNIFORMS_INVENTORY', 'موظف مخزن الملابس'), ('INVENTORY_MANAGER', 'مدير المخازن')], max_length=25),
        ),
    ]
