# Generated by Django 5.2.6 on 2026-06-06 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentsettings'),
        ('school_settings', '0006_alter_settingslog_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdiscount',
            options={'ordering': ['-created_date'], 'verbose_name': 'خصم الطالب', 'verbose_name_plural': 'خصومات الطلاب'},
        ),
        migrations.AddField(
            model_name='discountsettings',
            name='application_scope',
            field=models.CharField(choices=[('TOTAL_FEES', 'على إجمالي مصروفات الطالب'), ('PER_INSTALLMENT', 'على كل قسط'), ('FEE_TYPE_TOTAL', 'على إجمالي نوع مصروف معين')], default='PER_INSTALLMENT', help_text='حدد هل الخصم يطبق على إجمالي المصروفات أم على كل قسط أم على نوع مصروف معين', max_length=20, verbose_name='نطاق تطبيق الخصم'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='application_scope',
            field=models.CharField(choices=[('TOTAL_FEES', 'على إجمالي مصروفات الطالب'), ('PER_INSTALLMENT', 'على كل قسط'), ('FEE_TYPE_TOTAL', 'على إجمالي نوع مصروف معين')], default='PER_INSTALLMENT', max_length=20, verbose_name='نطاق التطبيق وقت الخصم'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='fee_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='نوع المصروف المطبق عليه'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='tuition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_discounts', to='payments.tuition', verbose_name='القسط المرتبط'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='applicable_to_fee_types',
            field=models.CharField(blank=True, help_text='اكتب أنواع المصروفات مفصولة بفواصل مثل: TUITION,BOOKS,TRANSPORT', max_length=200, verbose_name='أنواع المصروفات المطبق عليها'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='category',
            field=models.CharField(choices=[('SIBLING', 'خصم الأشقاء'), ('FINANCIAL_HARDSHIP', 'خصم الحالة المالية'), ('ACADEMIC_EXCELLENCE', 'خصم التفوق الأكاديمي'), ('STAFF_CHILDREN', 'خصم أبناء الموظفين'), ('EARLY_PAYMENT', 'خصم الدفع المبكر'), ('LOYALTY', 'خصم الولاء'), ('OTHER', 'خصومات أخرى')], max_length=30, verbose_name='فئة الخصم'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED_AMOUNT', 'مبلغ ثابت')], max_length=20, verbose_name='نوع الخصم'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأقصى لمبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='min_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للمبلغ لتطبيق الخصم'),
        ),
        migrations.AlterField(
            model_name='discountsettings',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='studentdiscount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studentdiscount',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
