# Generated by Django 5.2.6 on 2025-09-26 19:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0029_delete_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخصم')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخصم')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قيمة الخصم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل غرامة التأخير (%)')),
                ('grace_period_days', models.IntegerField(default=7, verbose_name='فترة السماح (أيام)')),
                ('default_installments_count', models.IntegerField(default=10, verbose_name='عدد الأقساط الافتراضي')),
                ('auto_generate_installments', models.BooleanField(default=True, verbose_name='إنشاء أقساط تلقائي')),
                ('currency_symbol', models.CharField(default='ج.م', max_length=5, verbose_name='رمز العملة')),
            ],
            options={
                'verbose_name': 'إعدادات المدفوعات',
                'verbose_name_plural': 'إعدادات المدفوعات',
            },
        ),
        migrations.CreateModel(
            name='OverdueTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي المتأخرات')),
                ('overdue_count', models.IntegerField(verbose_name='عدد الأقساط المتأخرة')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر دفع')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='تم إرسال تنبيه')),
                ('last_notification_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-total_overdue_amount'],
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='رقم القسط')),
                ('amount_tuition', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='مبلغ القسط')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='المبلغ المدفوع')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الاستحقاق')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('PAID', 'مدفوع'), ('OVERDUE', 'متأخر'), ('PARTIALLY_PAID', 'مدفوع جزئياً')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('check', 'شيك'), ('card', 'بطاقة ائتمان')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_user', models.CharField(default='account user', max_length=50, verbose_name='مسؤول الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('receipt_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الإيصال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('check', 'شيك'), ('card', 'بطاقة ائتمان')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_user', models.CharField(max_length=50, verbose_name='مسؤول الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الإيصال')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payments.tuition')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_by', models.CharField(max_length=50, verbose_name='تم التطبيق بواسطة')),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.discount')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'discount')},
            },
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['due_date', 'payment_status'], name='payments_tu_due_dat_5e34ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['student', 'due_date'], name='payments_tu_student_300880_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['payment_date'], name='payments_tu_payment_766e61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together={('student', 'installment_number')},
        ),
    ]
