# Generated by Django 5.2.6 on 2025-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('total_payments', models.IntegerField(default=0, verbose_name='عدد المدفوعات')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المبلغ')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المدفوعات النقدية')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التحويلات البنكية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ملخص المدفوعات اليومي',
                'verbose_name_plural': 'ملخصات المدفوعات اليومية',
                'ordering': ['-date'],
            },
        ),
    ]
