# Generated by Django 5.2.6 on 2025-10-01 09:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsummary'),
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0033_remove_comment_student_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuition',
            options={'ordering': ['-payment_date', '-created_date'], 'verbose_name': 'قسط مدرسي', 'verbose_name_plural': 'أقساط مدرسية'},
        ),
        migrations.RemoveIndex(
            model_name='tuition',
            name='payments_tu_due_dat_5e34ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='tuition',
            name='payments_tu_student_300880_idx',
        ),
        migrations.RemoveIndex(
            model_name='tuition',
            name='payments_tu_payment_766e61_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tuition',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='applied_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.studentdiscount', verbose_name='الخصم المطبق'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الخصم'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='fee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المصروفات'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='fee_type',
            field=models.CharField(choices=[('TUITION', 'مصروفات دراسية'), ('BOOKS', 'مصروفات كتب'), ('UNIFORMS', 'مصروفات ملابس'), ('TRANSPORT', 'مصروفات نقل'), ('MEALS', 'مصروفات وجبات'), ('ACTIVITIES', 'مصروفات أنشطة'), ('REGISTRATION', 'رسوم تسجيل'), ('OTHER', 'مصروفات أخرى')], default='TUITION', max_length=20, verbose_name='نوع المصروفات'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة ائتمان'), ('check', 'شيك')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='amount_tuition',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ القسط المطلوب'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='installment_number',
            field=models.PositiveIntegerField(verbose_name='رقم القسط'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة ائتمان'), ('check', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'معلق'), ('PAID', 'مدفوع'), ('PARTIALLY_PAID', 'مدفوع جزئياً'), ('OVERDUE', 'متأخر'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحاسب'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together={('student', 'fee_type', 'installment_number', 'academic_year')},
        ),
    ]
