# Generated by Django 5.2.6 on 2025-10-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_tuition_options_and_more'),
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0033_remove_comment_student_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overduetracking',
            name='student',
        ),
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
        migrations.DeleteModel(
            name='PaymentSummary',
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentdiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='studentdiscount',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_date'], 'verbose_name': 'خصم', 'verbose_name_plural': 'خصومات'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-payment_date'], 'verbose_name': 'سجل دفع', 'verbose_name_plural': 'سجلات الدفع'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='discount',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الخصم'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='discount',
            name='reason',
            field=models.TextField(blank=True, default='خصم عام', verbose_name='سبب الخصم'),
        ),
        migrations.AddField(
            model_name='discount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_user',
            field=models.CharField(max_length=100, verbose_name='المحاسب'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.tuition', verbose_name='القسط'),
        ),
        migrations.DeleteModel(
            name='OverdueTracking',
        ),
        migrations.DeleteModel(
            name='StudentDiscount',
        ),
    ]
