# Generated by Django 5.2.6 on 2026-06-05 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_overduetracking_student_and_more'),
        ('school_settings', '0006_alter_settingslog_description_and_more'),
        ('students', '0033_remove_comment_student_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_discounts', to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_discounts', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payments.tuition', verbose_name='القسط'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_payments', to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='applied_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_payments', to='school_settings.studentdiscount', verbose_name='الخصم المطبق'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم الإيصال'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_payments', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['student', 'academic_year'], name='payments_di_student_d75d97_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active'], name='payments_di_is_acti_04a39a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_f30b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_a26944_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['student', 'academic_year'], name='payments_tu_student_5aaeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['payment_status'], name='payments_tu_payment_04ac1a_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['payment_date'], name='payments_tu_payment_766e61_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['fee_type'], name='payments_tu_fee_typ_fd3add_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuition',
            constraint=models.UniqueConstraint(fields=('student', 'fee_type', 'installment_number', 'academic_year'), name='unique_student_fee_installment_year'),
        ),
    ]
