# Generated by Django 5.2.6 on 2026-06-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_tuition_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_ar', models.CharField(default='مدرسة المنار الخاصة للغات', max_length=200, verbose_name='اسم المدرسة بالعربية')),
                ('school_name_en', models.CharField(default='Al-Manar Private Language School', max_length=200, verbose_name='اسم المدرسة بالإنجليزية')),
                ('receipt_prefix', models.CharField(default='REC', max_length=20, verbose_name='بادئة رقم الإيصال')),
                ('receipt_footer_text', models.TextField(blank=True, default='هذا إيصال رسمي صادر من نظام إدارة المدفوعات. يرجى الاحتفاظ به كمرجع.', verbose_name='نص أسفل الإيصال')),
                ('default_payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة ائتمان'), ('check', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع الافتراضية')),
                ('daily_collection_target', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='هدف التحصيل اليومي')),
                ('monthly_collection_target', models.DecimalField(decimal_places=2, default=300000, max_digits=12, verbose_name='هدف التحصيل الشهري')),
                ('allow_overpayment', models.BooleanField(default=False, verbose_name='السماح بدفع مبلغ أكبر من المطلوب')),
                ('auto_generate_receipt_number', models.BooleanField(default=True, verbose_name='توليد رقم الإيصال تلقائيًا')),
                ('show_school_name_on_receipt', models.BooleanField(default=True, verbose_name='إظهار اسم المدرسة في الإيصال')),
                ('show_payment_records_on_receipt', models.BooleanField(default=True, verbose_name='إظهار سجل الدفعات في الإيصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المدفوعات',
                'verbose_name_plural': 'إعدادات المدفوعات',
            },
        ),
    ]
