# Generated by Django 4.1.3 on 2023-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('student_affairs', 'Student Affairs'), ('sub_admin', 'sub_admin'), ('administration', 'Administration')], max_length=20),
        ),
    ]
