# Generated by Django 5.2.6 on 2026-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_department_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_reports', 'Can view all reports'), ('can_edit_employee', 'Can edit employee profile'), ('can_add_student', 'Can add new student'), ('can_edit_student', 'Can edit student profile'), ('can_add_expense', 'Can add new expense'), ('can_pay_installment', 'Can pay student installment')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_enrollment',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الالتحاق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
