# Generated by Django 4.1.3 on 2023-06-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('year', models.CharField(default='2023', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('name', models.CharField(default='Default Classroom Name', max_length=100, null=True)),
                ('stage', models.CharField(choices=[('', 'اختار المرحلة التعليمية'), ('BC', 'مرحلة تمهيدي'), ('KG1', 'رياض أطفال 1'), ('KG2', 'رياض أطفال 2'), ('Prim1', 'الصف الأول الابتدائي'), ('Prim2', 'الصف الثاني الابتدائي'), ('Prim3', 'الصف الثالث الابتدائي'), ('Prim4', 'الصف الرابع الابتدائي'), ('Prim5', 'الصف الخامس الابتدائي'), ('Prim6', 'الصف السادس الابتدائي'), ('Prep7', 'الصف الأول الإعدادي'), ('Prep8', 'الصف الثاني الإعدادي'), ('Prep9', 'الصف الثالث الإعدادي'), ('Sec1', 'الصف الأول الثانوي'), ('Sec2', 'الصف الثاني الثانوي'), ('Sec3', 'الصف الثالث الثانوي')], default='default_value', max_length=50, null=True)),
                ('fee_per_student', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('name', models.CharField(choices=[('', 'اختار المرحلة الدراسية'), ('BC', 'babyclass'), ('Kindergarten', 'Kindergarten'), ('Primary Stage', 'Primary Stage'), ('Prep Stage', 'Prep Stage'), ('Secondary Stage', 'Secondary Stage')], default='default_value', max_length=50, null=True, verbose_name='Educational Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('name', models.CharField(max_length=50)),
                ('national_number', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('', '---------'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('academic_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear')),
                ('classroom', models.ManyToManyField(to='students.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('installment_number', models.IntegerField()),
                ('amount_tuition', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_user', models.CharField(default='account user', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('expense_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_expenses', to='students.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='educational_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.educationalstage'),
        ),
        migrations.CreateModel(
            name='ArchiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('name', models.CharField(max_length=50)),
                ('national_number', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('classroom', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear')),
            ],
        ),
    ]
