# Generated by Django 4.1.3 on 2023-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivestudent',
            name='classroom',
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='classroom',
            field=models.ManyToManyField(to='students.classroom'),
        ),
    ]
