# Generated by Django 4.1.3 on 2023-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_archivestudent_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivestudent',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='gender',
            field=models.CharField(choices=[('', '---------'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
