# Generated by Django 4.1.3 on 2023-06-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_archivestudent_total_owed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveStudent',
        ),
    ]
