# Generated by Django 4.1.3 on 2023-06-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_archivestudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveStudent',
        ),
    ]
