# Generated by Django 4.1.3 on 2023-06-22 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_archivestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivestudent',
            name='academic_year',
            field=models.ForeignKey(default=1 , on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1),
        ),
    ]
