# Generated by Django 4.1.3 on 2023-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_academicyear_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivestudent',
            old_name='academic_year',
            new_name='archive_academic_year',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='age',
            new_name='archive_age',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='classroom',
            new_name='archive_classroom',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='date_of_birth',
            new_name='archive_date_of_birth',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='gender',
            new_name='archive_gender',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='name',
            new_name='archive_name',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='national_number',
            new_name='archive_national_number',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='total_owed',
            new_name='archive_total_owed',
        ),
        migrations.RenameField(
            model_name='archivestudent',
            old_name='total_payments',
            new_name='archive_total_payments',
        ),
    ]
