# Generated by Django 4.1.3 on 2023-06-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_academicyear_id_alter_archivestudent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=15),
        ),
    ]
