# Generated by Django 4.1.3 on 2023-06-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
