# Generated by Django 4.1.3 on 2023-06-22 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_archivestudent_archive_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_academic_year',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
    ]
