# Generated by Django 4.1.3 on 2023-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='discount',
            field=models.CharField(choices=[('NONE', 'No Discount'), ('CHAIRMAN', 'Chairman of the Board Discount'), ('VICE_CHAIRMAN', 'Vice Chairman of the Board Discount'), ('EMPLOYEE_CHILD', 'Employee Child Discount'), ('ARMED_FORCES', 'Armed Forces Discount')], default='NONE', max_length=20),
        ),
    ]
