# Generated by Django 4.1.3 on 2023-06-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_expense_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='discount',
        ),
    ]
