# Generated by Django 4.1.3 on 2025-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_remove_expense_discount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['classroom', 'date'], name='students_ex_classro_62de65_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['national_number'], name='students_st_nationa_3ce59b_idx'),
        ),
    ]
