# Generated by Django 4.1.3 on 2025-09-24 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0026_expense_students_ex_classro_62de65_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الخصم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الخصم')),
                ('discount_method', models.CharField(choices=[('FIXED', 'مبلغ ثابت'), ('PERCENTAGE', 'نسبة مئوية')], max_length=10, verbose_name='طريقة الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخصم')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'مدير النظام'), ('SCHOOL_MANAGER', 'مدير المدرسة'), ('ACCOUNTANT', 'موظف الحسابات'), ('STUDENT_AFFAIRS', 'موظف شؤون الطلاب'), ('BOOKS_INVENTORY', 'موظف مخزن الكتب'), ('UNIFORMS_INVENTORY', 'موظف مخزن الملابس')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tuition',
            old_name='receipt_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='paid',
        ),
        migrations.AddField(
            model_name='tuition',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'في الانتظار'), ('PAID', 'مدفوع'), ('OVERDUE', 'متأخر'), ('PARTIALLY_PAID', 'مدفوع جزئياً')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='amount_tuition',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='مبلغ القسط'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='installment_number',
            field=models.IntegerField(verbose_name='رقم القسط'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_user',
            field=models.CharField(default='account user', max_length=50, verbose_name='مسؤول الدفع'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['due_date', 'payment_status'], name='students_tu_due_dat_86e3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tuition',
            index=models.Index(fields=['student', 'due_date'], name='students_tu_student_05779c_idx'),
        ),
        migrations.AddField(
            model_name='systemrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.discounttype'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='students.student'),
        ),
    ]
