# Generated by Django 4.1.3 on 2025-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_discounttype_studentdiscount_systemrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdiscount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='studentdiscount',
            name='student',
        ),
        migrations.RemoveField(
            model_name='systemrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscountType',
        ),
        migrations.DeleteModel(
            name='StudentDiscount',
        ),
        migrations.DeleteModel(
            name='SystemRole',
        ),
    ]
