# Generated by Django 5.2.6 on 2025-09-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_remove_studentdiscount_discount_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuition',
        ),
    ]
