# Generated by Django 5.2.6 on 2025-09-27 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0029_delete_tuition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'العام الدراسي (قديم)', 'verbose_name_plural': 'الأعوام الدراسية (قديم)'},
        ),
        migrations.AlterModelOptions(
            name='archivestudent',
            options={'verbose_name': 'طالب مؤرشف', 'verbose_name_plural': 'الطلاب المؤرشفون'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'الفصل الدراسي (قديم)', 'verbose_name_plural': 'الفصول الدراسية (قديم)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'تعليق', 'verbose_name_plural': 'التعليقات'},
        ),
        migrations.AlterModelOptions(
            name='educationalstage',
            options={'verbose_name': 'المرحلة التعليمية (قديم)', 'verbose_name_plural': 'المراحل التعليمية (قديم)'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'مصروفات', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='settings_academic_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.academicyear', verbose_name='العام في نظام الإعدادات'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archived_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='settings_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.gradelevel', verbose_name='الصف في نظام الإعدادات'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='educationalstage',
            name='settings_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.educationlevel', verbose_name='المرحلة في نظام الإعدادات'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد ولي الأمر'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم ولي الأمر'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف ولي الأمر'),
        ),
        migrations.AddField(
            model_name='student',
            name='settings_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.gradelevel', verbose_name='الصف (نظام الإعدادات)'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_gender',
            field=models.CharField(choices=[('', '---------'), ('M', 'ذكر'), ('F', 'أنثى')], max_length=1),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_national_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(to='students.classroom', verbose_name='الفصول الدراسية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'اختر الجنس'), ('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_owed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='إجمالي المستحقات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='إجمالي المدفوعات'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='students_st_name_0bae46_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='students_st_created_78a19f_idx'),
        ),
    ]
