# Generated by Django 5.2.6 on 2025-09-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0031_alter_student_age_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='settings_academic_year',
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_academic_year',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='educational_stage',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='settings_grade_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='archivestudent',
            name='archive_classroom',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='educationalstage',
            name='settings_education_level',
        ),
        migrations.AlterModelOptions(
            name='archivestudent',
            options={'ordering': ['-archived_date'], 'verbose_name': 'طالب مؤرشف', 'verbose_name_plural': 'الطلاب المؤرشفون'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='settings_grade_level',
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_education_level',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='المرحلة التعليمية'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_grade_level',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archived_reason',
            field=models.CharField(blank=True, default='غير محدد', max_length=100, verbose_name='سبب الأرشفة'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.gradelevel', verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_age',
            field=models.IntegerField(default=0, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_gender',
            field=models.CharField(choices=[('', '---------'), ('M', 'ذكر'), ('F', 'أنثى')], default='', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_name',
            field=models.CharField(max_length=100, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_national_number',
            field=models.CharField(max_length=14, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المستحقات'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المدفوعات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المستحقات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المدفوعات'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade_level'], name='students_st_grade_l_3bfe0b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year'], name='students_st_academi_c3b18f_idx'),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='EducationalStage',
        ),
    ]
