# Generated by Django 5.2.6 on 2025-09-30 14:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        ('students', '0032_remove_academicyear_settings_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الأرشفة بواسطة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_gender',
            field=models.CharField(choices=[('', 'غير محدد'), ('M', 'ذكر'), ('F', 'أنثى')], default='', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archived_reason',
            field=models.CharField(default='غير محدد', max_length=200, verbose_name='سبب الأرشفة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='العام الدراسي للتسجيل', null=True, on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, help_text='سيتم حسابه تلقائياً من الرقم القومي', null=True, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='سيتم استخراجه تلقائياً من الرقم القومي', null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'اختر الجنس'), ('M', 'ذكر'), ('F', 'أنثى')], help_text='سيتم استخراجه تلقائياً من الرقم القومي', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='الصف الدراسي الحالي', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.gradelevel', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الطالب نشط في النظام؟', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='الاسم الرباعي للطالب', max_length=100, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مجموع الرسوم المستحقة', max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='المبلغ المتبقي للسداد', max_digits=12, verbose_name='إجمالي المستحقات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مجموع ما تم دفعه من رسوم', max_digits=12, verbose_name='إجمالي المدفوعات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='students_st_is_acti_c00e81_idx'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
