# Generated by Django 5.2.6 on 2026-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0007_alter_studentdiscount_options_and_more'),
        ('students', '0033_remove_comment_student_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivestudent',
            name='archive_disability_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نوع الإعاقة'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_educational_guardian',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='صاحب الولاية التعليمية'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_educational_guardian_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم صاحب الولاية التعليمية'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_enrollment_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='حالة القيد'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_father_job',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='وظيفة الأب'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_is_integration_student',
            field=models.BooleanField(default=False, verbose_name='طالب دمج / من ذوي الهمم'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_is_staff_child',
            field=models.BooleanField(default=False, verbose_name='من أبناء العاملين'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_nationality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_parent_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم ولي الأمر'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_parent_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='هاتف ولي الأمر'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_passport_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم جواز السفر'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_religion',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الديانة'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_staff_parent_job',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='وظيفة الموظف'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_staff_parent_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_student_type',
            field=models.CharField(blank=True, default='طالب عادي', max_length=50, verbose_name='نوع الطالب'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_subject_exemptions',
            field=models.TextField(blank=True, default='', verbose_name='إعفاءات المواد'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_transferred_from_school',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='محول من مدرسة'),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='archive_transferred_to_school',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='محول إلى مدرسة'),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع الإعاقة'),
        ),
        migrations.AddField(
            model_name='student',
            name='educational_guardian',
            field=models.CharField(blank=True, choices=[('FATHER', 'الأب'), ('MOTHER', 'الأم'), ('OTHER', 'آخر')], default='FATHER', max_length=20, verbose_name='صاحب الولاية التعليمية'),
        ),
        migrations.AddField(
            model_name='student',
            name='educational_guardian_name',
            field=models.CharField(blank=True, help_text='يستخدم إذا كانت الولاية التعليمية لشخص آخر غير الأب أو الأم', max_length=150, verbose_name='اسم صاحب الولاية التعليمية'),
        ),
        migrations.AddField(
            model_name='student',
            name='educational_guardian_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف صاحب الولاية التعليمية'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('NEW', 'مستجد'), ('PROMOTED', 'ناجح ومنقول'), ('TRANSFERRED', 'محول'), ('REPEATER', 'باق للإعادة')], default='NEW', max_length=20, verbose_name='حالة القيد'),
        ),
        migrations.AddField(
            model_name='student',
            name='exempt_from_arabic',
            field=models.BooleanField(default=False, verbose_name='إعفاء من اللغة العربية'),
        ),
        migrations.AddField(
            model_name='student',
            name='exempt_from_english',
            field=models.BooleanField(default=False, verbose_name='إعفاء من اللغة الإنجليزية'),
        ),
        migrations.AddField(
            model_name='student',
            name='exempt_from_french',
            field=models.BooleanField(default=False, verbose_name='إعفاء من اللغة الفرنسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, max_length=150, verbose_name='وظيفة الأب'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_integration_student',
            field=models.BooleanField(default=False, verbose_name='طالب دمج / من ذوي الهمم'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_staff_child',
            field=models.BooleanField(default=False, verbose_name='من أبناء العاملين'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_subject_exemptions',
            field=models.TextField(blank=True, help_text='اكتب أي مواد أخرى معفَى منها الطالب', verbose_name='إعفاءات أخرى من مواد'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, help_text='اختياري، ويستخدم غالباً للطلاب الوافدين', max_length=50, null=True, unique=True, verbose_name='رقم جواز السفر'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('', 'غير محدد'), ('MUSLIM', 'مسلم'), ('CHRISTIAN', 'مسيحي'), ('OTHER', 'أخرى')], default='', max_length=20, verbose_name='الديانة'),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_parent_job',
            field=models.CharField(blank=True, max_length=150, verbose_name='وظيفة الموظف داخل المدرسة'),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_parent_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم الموظف من العاملين'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'طالب عادي'), ('EXPATRIATE', 'وافد')], default='REGULAR', max_length=20, verbose_name='نوع الطالب'),
        ),
        migrations.AddField(
            model_name='student',
            name='transferred_from_school',
            field=models.CharField(blank=True, help_text='اسم المدرسة السابقة إذا كان الطالب محولاً إلى المدرسة', max_length=200, verbose_name='محول من مدرسة'),
        ),
        migrations.AddField(
            model_name='student',
            name='transferred_to_school',
            field=models.CharField(blank=True, help_text='اسم المدرسة الجديدة إذا تم تحويل الطالب خارج المدرسة', max_length=200, verbose_name='محول إلى مدرسة'),
        ),
        migrations.AlterField(
            model_name='archivestudent',
            name='archive_national_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, help_text='يتم حسابه تلقائياً من الرقم القومي أو تاريخ الميلاد إن وجد', null=True, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='يتم استخراجه تلقائياً من الرقم القومي إذا أمكن', null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'اختر الجنس'), ('M', 'ذكر'), ('F', 'أنثى')], help_text='يتم استخراجه تلقائياً من الرقم القومي إذا لم يتم تحديده', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_number',
            field=models.CharField(blank=True, help_text='اختياري للوافدين، ويجب أن يكون 14 رقماً عند إدخاله', max_length=14, null=True, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['passport_number'], name='students_st_passpor_bdd713_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_type'], name='students_st_student_71c8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_status'], name='students_st_enrollm_7bd618_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_integration_student'], name='students_st_is_inte_b88fec_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_staff_child'], name='students_st_is_staf_e993f1_idx'),
        ),
    ]
