# Generated by Django 5.2.6 on 2025-09-29 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_settings', '0004_systemrole_permissions_alter_systemrole_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('category_type', models.CharField(choices=[('REVENUE', 'إيرادات'), ('EXPENSE', 'مصروفات'), ('ASSET', 'أصول'), ('LIABILITY', 'خصوم')], max_length=15, verbose_name='نوع التصنيف')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury_management.accountcategory', verbose_name='التصنيف الرئيسي')),
            ],
            options={
                'verbose_name': 'تصنيف الحساب',
                'verbose_name_plural': 'تصنيفات الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحساب')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='كود الحساب')),
                ('description', models.TextField(blank=True, verbose_name='وصف الحساب')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.accountcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'حساب مالي',
                'verbose_name_plural': 'الحسابات المالية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية الشهرية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.account', verbose_name='الحساب المرتبط')),
            ],
            options={
                'verbose_name': 'تصنيف المصروفات',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='رقم العملية')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'إيراد'), ('EXPENSE', 'مصروف'), ('TRANSFER', 'تحويل')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='وصف العملية')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHECK', 'شيك'), ('CREDIT_CARD', 'كارت ائتماني'), ('OTHER', 'أخرى')], default='CASH', max_length=15, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المرجع')),
                ('related_model', models.CharField(blank=True, max_length=50, verbose_name='النموذج المرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف السجل المرتبط')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ العملية')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمدة')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغية')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_settings.academicyear', verbose_name='العام الدراسي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.account', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنshأ بواسطة')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.transaction', verbose_name='العملية المالية')),
            ],
            options={
                'verbose_name': 'عملية دفع طالب',
                'verbose_name_plural': 'عمليات دفع الطلاب',
            },
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=20, unique=True, verbose_name='رقم المصروف')),
                ('expense_type', models.CharField(choices=[('SALARIES', 'مرتبات'), ('UTILITIES', 'مرافق'), ('SUPPLIES', 'مستلزمات'), ('MAINTENANCE', 'صيانة'), ('MARKETING', 'دعاية'), ('TRANSPORTATION', 'نقل'), ('OTHER', 'أخرى')], max_length=15, verbose_name='نوع المصروف')),
                ('description', models.TextField(verbose_name='وصف المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('vendor_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المورد')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المصروف')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.expensecategory', verbose_name='التصنيف')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury_management.transaction', verbose_name='العملية المالية')),
            ],
            options={
                'verbose_name': 'مصروف يومي',
                'verbose_name_plural': 'المصروفات اليومية',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخزنة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود الخزنة')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع')),
                ('max_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأقصى')),
                ('min_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الحد الأدنى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.account', verbose_name='الحساب المالي')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'خزنة',
                'verbose_name_plural': 'الخزائن',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.treasury', verbose_name='الخزنة'),
        ),
        migrations.CreateModel(
            name='TreasurySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='تاريخ اللقطة')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الختامي')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المصروفات')),
                ('transactions_count', models.IntegerField(default=0, verbose_name='عدد العمليات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury_management.treasury', verbose_name='الخزنة')),
            ],
            options={
                'verbose_name': 'لقطة الخزنة اليومية',
                'verbose_name_plural': 'لقطات الخزنة اليومية',
                'ordering': ['-snapshot_date'],
                'unique_together': {('treasury', 'snapshot_date')},
            },
        ),
    ]
