# Generated by Django 5.2.6 on 2025-09-29 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['code'], 'verbose_name': 'تصنيف المصروفات', 'verbose_name_plural': 'تصنيفات المصروفات'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود التصنيف'),
        ),
    ]
