# Generated by Django 5.2.6 on 2026-06-02 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_management', '0002_alter_expensecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة')),
                ('min_payment', models.DecimalField(decimal_places=2, default=50, max_digits=12, verbose_name='أقل مبلغ دفع')),
                ('max_payment', models.DecimalField(decimal_places=2, default=5000, max_digits=12, verbose_name='أكبر مبلغ دفع')),
                ('require_approval', models.BooleanField(default=False, verbose_name='يتطلب اعتماد العمليات')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل التنبيهات')),
                ('report_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='لغة التقارير')),
                ('date_format', models.CharField(default='d/m/Y', max_length=20, verbose_name='تنسيق التاريخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات الخزينة',
                'verbose_name_plural': 'إعدادات الخزينة',
            },
        ),
    ]
