# Generated by Django 5.2.6 on 2026-06-03 00:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0006_alter_settingslog_description_and_more'),
        ('treasury_management', '0003_treasurysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(verbose_name='تاريخ القفل')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد بداية اليوم')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الداخل')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الخارج')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد نهاية اليوم')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القفل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'قفل يومية',
                'verbose_name_plural': 'قفل اليوميات',
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الجرد')),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الدفتري')),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الفعلي')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الفرق')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الفرق')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'جرد خزنة',
                'verbose_name_plural': 'جرد الخزائن',
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'ordering': ['name'], 'verbose_name': 'خزنة', 'verbose_name_plural': 'الخزائن'},
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ألغيت بواسطة'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('STUDENT_FEES', 'مصروفات دراسية'), ('BUS_FEES', 'إيرادات الباص'), ('ACTIVITY_FEES', 'إيرادات الأنشطة'), ('BOOKS_SALES', 'إيرادات الكتب'), ('UNIFORM_SALES', 'إيرادات الزي'), ('OTHER_INCOME', 'إيراد آخر'), ('DAILY_EXPENSE', 'مصروف يومي'), ('SALARY', 'مرتبات'), ('MAINTENANCE', 'صيانة'), ('UTILITIES', 'مرافق'), ('SUPPLIES', 'مستلزمات'), ('TRANSPORTATION', 'نقل'), ('OTHER_EXPENSE', 'مصروف آخر'), ('TRANSFER', 'تحويل بين الخزائن'), ('ADJUSTMENT', 'تسوية / جرد')], max_length=30, verbose_name='مصدر العملية'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='treasury_management.treasury', verbose_name='الخزنة المحول إليها'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='treasury_management.accountcategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='category_type',
            field=models.CharField(choices=[('REVENUE', 'إيرادات'), ('EXPENSE', 'مصروفات'), ('ASSET', 'أصول'), ('LIABILITY', 'خصوم'), ('EQUITY', 'حقوق الملكية')], max_length=15, verbose_name='نوع التصنيف'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود التصنيف'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treasury_management.accountcategory', verbose_name='التصنيف الرئيسي'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='treasury_management.expensecategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_expenses', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المصروف'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='expense_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم المصروف'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='expense_type',
            field=models.CharField(choices=[('SALARIES', 'مرتبات'), ('UTILITIES', 'مرافق'), ('SUPPLIES', 'مستلزمات'), ('MAINTENANCE', 'صيانة'), ('MARKETING', 'دعاية'), ('TRANSPORTATION', 'نقل'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع المصروف'),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_expense', to='treasury_management.transaction', verbose_name='العملية المالية'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='treasury_management.account', verbose_name='الحساب المرتبط'),
        ),
        migrations.AlterField(
            model_name='studentpaymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studentpaymenttransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_link', to='treasury_management.transaction', verbose_name='العملية المالية'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_settings.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='treasury_management.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHECK', 'شيك'), ('CREDIT_CARD', 'كارت ائتماني'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم العملية'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='treasury_management.treasury', verbose_name='الخزنة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury', to='treasury_management.account', verbose_name='الحساب المالي'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الخزنة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AlterField(
            model_name='treasurysnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='treasurysnapshot',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='treasury_management.treasury', verbose_name='الخزنة'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'is_approved', 'is_cancelled'], name='treasury_ma_transac_218c56_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='treasury_ma_transac_7f2a64_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['treasury'], name='treasury_ma_treasur_44f627_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_type'], name='treasury_ma_source__c29b25_idx'),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أغلق بواسطة'),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closings', to='treasury_management.treasury', verbose_name='الخزنة'),
        ),
        migrations.AddField(
            model_name='treasuryreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='تم الاعتماد بواسطة'),
        ),
        migrations.AddField(
            model_name='treasuryreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='تم الجرد بواسطة'),
        ),
        migrations.AddField(
            model_name='treasuryreconciliation',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='treasury_management.treasury', verbose_name='الخزنة'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyclosing',
            unique_together={('treasury', 'closing_date')},
        ),
    ]
